### ISSUE TITLE
vim-colorscheme-primary : Unable to install plugin

### ISSUE THREAD

**Issue by FriendOfFatBeagle** [google/vim-colorscheme-primary#5]
Hello:

I am new to Vim. In fact, just completed Vimtutor today.
I am trying to add colorscheme.
I HAVE NOT DOWNLOAD ANYTHING FROM YOUR PAGE YET.

I did this in in FILE, /etc/vim/vimrc :
"====== Begin: MyPlugins =================
Plugin 'google/vim-colorscheme-primary'
"======== End: MyPlugins ==========

The above file includes pasted code from Vundle, https://github.com/gmarik/Vundle.vim#quick-start

and also added this:
set t_Co=256
syntax on
set background=dark
colorscheme primary

When I ran vim like so, I got this error:

sudo vim /etc/vim/vimrc
Error detected while processing /usr/share/vim/vimrc:
line 56:
E185: Cannot find color scheme 'primary'
Press ENTER or type command to continue
================= =======================
Question:
What did I missed?
Do I have to execute this first:
git clone https://github.com/google/vim-colorscheme-primary.vim.git ~/.vim/plugin/

OR does Vundle do it automatically install your plugin when I ran vim?
Thanks.

**Comment by xanderman** [comment]
Have you run :VundleInstall since you added the plugin line to your vimrc. This sounds like you haven't actually downloaded the plugin. (I wish Vundle warned you about missing plugin directories, but this is the wrong tracker for that.

**Comment by LisieRae** [comment]
If you are having trouble with Vundle, you can always just download the file primary.vim and save it in your ~/.vim/colors directory. (Create the folder if it doesn't already exist.) Vim knows to look for color schemes there.

**Comment by FriendOfFatBeagle** [comment]
@LisieRae :    
When you wrote 
"(Create the folder (~/.vim/colors) if it doesn't already exist.)  Vim knows to look for color schemes there."

I am very new to Vim.
Does this means for any color plugins, Vim always look for predefined subfolder ~/.vim/colors ?
Meaning Vim has already designated subfolder, colors, for all color realted stuff.

Or does it mean each plugin has its own plugin author created folder name, PluginFolderName, 
under ~/.vim/PluginFolderName  ?

This may help me understand more...
Do you know of which documentation discuss how Vim search for plugins 
or how VBundle search for plugins ?

I have read VBundle's quick start, and I am obviously did not understand how it operates in terms of 
searching and installing plugins.

Thanks.

**Comment by LisieRae** [comment]
Your first guess is correct. Vim always looks in the specific folder ~/.vim/colors for any color scheme files. Just save primary.vim there and Vim will be able to find it. 

As for Vundle, I'm also new to Vundle, so maybe someone else can answer that question.

**Comment by karthie** [comment]
hi 
If you are new to Vim i would suggest you to follow focusing on learning Vim through vimcast before you customise it.
If you prefer to customise vim please follow https://github.com/tpope/vim-pathogen install pathogen and 
install vim plugins in the ./vim/bundle folder using git clone https://github.com/uname/repo.git and restart vim in terminal.
I am not a big vundle enthusiast as you need to tinker with your .vimrc every time.
If you need any thing to do with vim customisation you need to do it in ~/.vimrc file as /etc is system vim.
Hope this helps.

**Comment by xanderman** [comment]
For a different perspective, I prefer Vundle to Pathogen because I prefer the configuration live in my vimrc. I support or vim users at work, and a common source of problems is pathogen users surprised to discover that some plugin they thought they'd removed is still running and now conflicting with something new. Vundle doesn't have that problem because there's a list in your vimrc of all the active plugins, and disabling one is as simple as removing a line. Vundle also make bulk updating your plugins easier, and provides a command to remove the plugin files you aren't using anymore.

**Comment by ehrktia** [comment]
thanks Xanderman i didnot knew about this pathogen issue , thanks for your insight i will try vundle.
I prefer not to mess up with vimrc every time.
Seems your idea is neat and effective will try to check vundle.

**Comment by FriendOfFatBeagle** [comment]
Thanks Xanderman, LisaRae, & ehrktia.
Sorry about the late reply .....
I am now back to  setting up my Vim.
"Have you run :VundleInstall since you added the plugin line to your vimrc.?"  ==>  Yes.

I will probably have more questions later.

If you folks have a .vimrc for javascript setup, I would not mind taking a peek.

**Comment by FriendOfFatBeagle** [comment]
I have successfully installed plugin 'google/vim-colorscheme-primary'.
Below is listed using Vundle command        : PluginList

" My Plugins
Plugin 'gmarik/Vundle.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'rstacruz/sparkup'
Plugin 'google/vim-colorscheme-primary'

But when I ran:
gvim .vimrc

I got this error:

> ~/.vim $ gvim vimrc
Error detected while processing /home/foffb/.vim/vimrc:
line   44:
E185: Cannot find color scheme 'primary'
> ~/.vim $ ls
bundle  vimrc
> ~/.vim $ cd bundle
 > ~/.vim/bundle $ ls
sparkup  vim-colorscheme-primary  vim-fugitive  Vundle.vim
> ~/.vim/bundle $ cd vim-colorscheme-primary/
> ~/.vim/bundle/vim-colorscheme-primary $ ls
colors  CONTRIBUTING.md  doc  LICENSE.md  README.md  screenshots
> ~/.vim/bundle/vim-colorscheme-primary $

What did I missed now?

**Comment by xanderman** [comment]
Ah, I think I see your new problem. The configuration steps (everything between 'syntax enable' and 'colorscheme primary') need to go after 'call vundle#end()'. end() is where vundle actually updates your runtimepath, so the plugins aren't available until after that point.

For plugins that only use global variables for configuration, where you put them doesn't matter. But for plugins that have to be available before you can set them up (like this, or something that supplies functions you call in your vimrc) you have to put the configuration after vundle#end().

**Comment by FriendOfFatBeagle** [comment]
Thanks. Xanderman.  It works.
I wish the docs were more specific, but may be I missed it..... 

What does "Xanderman" mean?
 
I am trying to setup  vimrc for avascript, if you have setup for javascript, 
do you mind me asking more questions here?

Again, thanks.

**Comment by FriendOfFatBeagle** [comment]
>>  For plugins that only use global variables for configuration .....  
How do we know if a plugin use global variables?
I thought the settings for color are global since it is used for the entire editor's content.

**Comment by xanderman** [comment]
The docs could probably be a little clearer, both here and for Vundle. I'll see what I can do.

Plugins that use global variables will tell you to put lines like 'let g:some_plugin_setting = value' in your vimrc. Since it won't read those variables until well after your vimrc is done, it doesn't really matter where you put them. But generally it's a good idea to have all your Plugin commands in one block, followed by 'call vundle#end()', and then other configurations. That way you're sure things are ready to be configured, and you only have one place to look to add/remove plugins.

I don't typically do javascript, so I don't have any special configuration for it. I'm betting you'll get better ideas from StackExchange (and a much broader group to query, too).

I use xanderman because all the usernames I would normally have chosen were already taken. I have a very common American name, but my high school girlfriend (for reasons known only to her) called me Xander.

**Comment by FriendOfFatBeagle** [comment]
I finally got things going, sort of.....
Thanks for all the help.
